import React, {useMemo, useState} from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowRight, CalendarDays, Check, ChevronRight, Clock3, Coffee, CreditCard, MapPin, Pause, Settings2, Users, X } from 'lucide-react';
import './styles.css';

const zones=['Porta Venezia','Isola','Navigli','Città Studi','Porta Romana','CityLife','Centrale','Lambrate'];
const slots=['Mar · 7:45','Mar · 8:30','Gio · 7:45','Gio · 8:30'];
const demoPeople=[
  {name:'Arianna',job:'Architetta',gender:'D',age:32},{name:'Luca',job:'Product designer',gender:'U',age:36},{name:'Marta',job:'Avvocata',gender:'D',age:29},{name:'Davide',job:'Fotografo',gender:'U',age:41},{name:'Elena',job:'Ricercatrice',gender:'D',age:34}
];

function Logo(){return <div className="logo">Coffee<span>Meeting</span></div>}
function Label({children,tone='green'}){return <span className={`eyebrow ${tone}`}>{children}</span>}
function Button({children,variant='primary',...p}){return <button className={`btn ${variant}`} {...p}>{children}</button>}
function Placeholder({children='foto reale: tavolo di colazione, luce del mattino'}){return <div className="photo-placeholder"><span>{children}</span></div>}

function PublicHome({go}){
 const steps=[['Indichi zona e slot','Scegli gli orari che reggi senza sveglie eroiche e la zona vicino a casa o all’ufficio.'],['Componiamo il tavolo','Da 4 a 6 persone, oppure uno a uno. Nessun profilo da sfogliare prima di arrivare.'],['Ricevi l’invito e confermi','Vedi giorno, ora, locale e numero di persone. La colazione si paga in anticipo.'],['Colazione, poi al lavoro','Circa 45 minuti insieme. Dopo, un riscontro anonimo di pochi secondi.']];
 return <main>
   <nav className="topbar"><Logo/><button className="linkbtn" onClick={()=>go('login')}>Accedi</button></nav>
   <section className="hero page-pad"><Label>MILANO · PRIMA DEL LAVORO</Label><h1>Una colazione con persone che non conosci.</h1><p className="lede">Scegli la zona e gli orari che ti vanno bene. Chi siede al tavolo e in quale locale lo decidiamo noi. Tu arrivi, ordini, parli. Alle nove sei al lavoro.</p><Button onClick={()=>go('signup')}>Iscriviti alla lista d’attesa <ArrowRight size={18}/></Button><p className="quiet">Non è un’app di incontri. Non scegli le persone, e nessuno sceglie te.</p></section>
   <div className="page-pad"><Placeholder/></div>
   <section className="page-pad section"><Label tone="muted">COME FUNZIONA</Label><h2>Quattro passaggi, nessuna scelta difficile.</h2><div className="steps">{steps.map((s,i)=><div className="step" key={s[0]}><span>{i+1}</span><div><strong>{s[0]}</strong><p>{s[1]}</p></div></div>)}</div></section>
   <section className="page-pad"><div className="dark-card"><Label>IN PRATICA</Label><div className="facts"><div><small>Slot fissi</small><b>Mar e gio, 7:45 o 8:30</b></div><div><small>Al tavolo</small><b>4–6 persone, o 2</b></div><div><small>Abbonamento</small><b><em>[DA DEFINIRE]</em> / mese</b></div><div><small>Colazione</small><b><em>[DA DEFINIRE]</em> prepagata</b></div></div><p>Disdetta gratuita fino a 12 ore prima. Dopo, la colazione non è rimborsabile: al tavolo qualcuno ti aspetta.</p></div></section>
   <section className="page-pad section"><Label tone="muted">COSA NON TROVI</Label><div className="no-list"><p>— Profili da sfogliare o foto da giudicare.</p><p>— Filtri per genere, età o aspetto.</p><p>— Chat da trascinare per giorni prima di incontrarsi.</p><p>— “Connessioni” da accumulare. Il punto è sedersi davvero.</p></div></section>
   <section className="page-pad final-cta"><h2>Il prossimo tavolo può iniziare da qui.</h2><Button onClick={()=>go('signup')}>Entra in lista d’attesa</Button></section>
 </main>
}

function Signup({go}){
 const [zone,setZone]=useState('Isola'); const [selected,setSelected]=useState(['Gio · 7:45']); const [fmt,setFmt]=useState('Entrambi');
 const toggle=s=>setSelected(v=>v.includes(s)?v.filter(x=>x!==s):[...v,s]);
 return <main><nav className="topbar"><Logo/><button className="linkbtn" onClick={()=>go('home')}>Chiudi</button></nav><section className="page-pad form-page"><Label>LISTA D’ATTESA</Label><h1>Dimmi quando e dove ti viene comodo.</h1><p className="lede">Non scegli le persone. Queste informazioni ci servono solo per capire quando possiamo comporre un tavolo.</p>
 <div className="form-stack"><label>Nome<input placeholder="Il tuo nome"/></label><label>Email<input placeholder="nome@esempio.it" type="email"/></label><label>Che lavoro fai<input placeholder="Es. restauratrice, backend developer"/></label>
 <div className="soft-card"><strong>Genere e anno di nascita</strong><div className="option-grid"><button>Donna</button><button>Uomo</button><button>Non binario</button><button>Preferisco non dirlo</button></div><input placeholder="Anno di nascita · es. 1990"/><p className="hint">Servono solo a comporre tavoli equilibrati. Nessun iscritto li vedrà.</p></div>
 <fieldset><legend>Zona comoda <small>una</small></legend><div className="pills">{zones.map(z=><button className={zone===z?'active':''} onClick={()=>setZone(z)} key={z}>{z}</button>)}</div></fieldset>
 <fieldset><legend>Slot preferiti <small>anche più di uno</small></legend><div className="slot-grid">{slots.map(s=><button className={selected.includes(s)?'active':''} onClick={()=>toggle(s)} key={s}>{s}</button>)}</div></fieldset>
 <fieldset><legend>Formato</legend><div className="choice-stack">{['Tavolo di gruppo','Uno a uno','Entrambi'].map(f=><button className={fmt===f?'active':''} onClick={()=>setFmt(f)} key={f}><span>{f}</span><small>{f==='Entrambi'?'decide la piattaforma':f==='Tavolo di gruppo'?'4–6 persone':'2 persone'}</small></button>)}</div></fieldset>
 <p className="hint">Inviando accetti puntualità, rispetto e disdetta entro 12 ore. Non condividiamo i tuoi dati con gli altri iscritti.</p><Button onClick={()=>go('waiting')}>Entra in lista d’attesa</Button></div></section></main>
}

function Waiting({go}){return <main><nav className="topbar"><Logo/><span className="quiet">Profilo</span></nav><section className="page-pad status-page"><Label tone="terra">IN LISTA D’ATTESA</Label><h1>Ci sei. Ora aspettiamo il tavolo giusto.</h1><p className="lede">Apriamo una zona quando ci sono abbastanza persone negli stessi slot. Ti scriviamo quando approviamo la tua iscrizione. Poi attivi l’abbonamento e inizi a ricevere inviti.</p><div className="summary-card"><div><span>Zona</span><b>Isola</b></div><div><span>Slot</span><b>Gio 7:45 · Mar 8:30</b></div><div><span>Formato</span><b>Entrambi</b></div></div><p className="hint">Più slot scegli, prima ti troviamo un posto.</p><Button variant="outline" onClick={()=>go('signup')}>Modifica preferenze</Button></section></main>}

function Login({go}){const [sent,setSent]=useState(false);return <main><nav className="topbar"><Logo/><button className="linkbtn" onClick={()=>go('home')}>Chiudi</button></nav><section className="page-pad auth-page"><Label>ACCESSO</Label><h1>{sent?'Controlla la posta.':'Entra senza password.'}</h1>{!sent?<><p className="lede">Ti mandiamo un link monouso valido 15 minuti.</p><label>Email<input placeholder="nome@esempio.it" type="email"/></label><Button onClick={()=>setSent(true)}>Mandami il link</Button></>:<><p className="lede">Abbiamo inviato un link a <b>nome@esempio.it</b>. Vale 15 minuti e funziona una volta sola.</p><Button onClick={()=>go('member')}>Apri demo iscritto</Button><button className="linkbtn">Rimanda il link</button></>}</section></main>}

function MemberHome({go}){return <main><nav className="topbar"><Logo/><button className="avatar" onClick={()=>go('founder')}>AM</button></nav><section className="page-pad member-head"><Label>GIOVEDÌ, 1 OTTOBRE</Label><h1>Buongiorno, Andrea.</h1></section><section className="page-pad"><div className="invite-card"><div className="invite-top"><Label>PROSSIMO INVITO</Label><span className="deadline">rispondi entro mar 29 · 20:00</span></div><div className="date-big"><strong>Gio 1</strong><span>ottobre · 7:45</span></div><div className="mini-row"><MapPin size={18}/><div><b>L’ile Douce</b><small>Via Luigi Porro Lambertenghi 15 · Isola</small></div></div><div className="mini-row"><Users size={18}/><div><b>5 persone</b><small>tu compreso</small></div></div><Button onClick={()=>go('invite')}>Apri l’invito <ChevronRight size={18}/></Button></div></section><section className="page-pad dashboard-grid"><div className="small-card"><Coffee/><small>Colazioni fatte</small><strong>7</strong></div><div className="small-card"><CreditCard/><small>Abbonamento</small><strong>Attivo</strong><span>rinnovo 14 ott</span></div></section><section className="page-pad"><div className="summary-card"><div><span>Zona</span><b>Isola</b></div><div><span>Slot</span><b>Gio 7:45 · Mar 8:30</b></div><div><span>Formato</span><b>Entrambi</b></div></div><Button variant="ghost"><Pause size={18}/> Metti in pausa gli inviti</Button></section></main>}

function Invitation({go}){const [paid,setPaid]=useState(false); const [cancel,setCancel]=useState(false); if(cancel) return <main><nav className="topbar"><Logo/></nav><section className="page-pad auth-page"><Label tone="terra">DISDETTA</Label><h1>Vuoi davvero liberare il posto?</h1><p className="lede">Se disdici entro mercoledì 30 settembre, 19:45, ricevi il rimborso completo. Dopo quell’ora la colazione non è rimborsabile.</p><Button variant="danger" onClick={()=>go('member')}>Sì, disdici</Button><Button variant="outline" onClick={()=>setCancel(false)}>Torna all’invito</Button></section></main>;
 return <main><nav className="topbar"><Logo/><button className="linkbtn" onClick={()=>go('member')}>Chiudi</button></nav><section className="page-pad invite-detail"><Label>{paid?'CONFERMATO · PAGATO':'INVITO'}</Label><div className="date-big hero-date"><strong>Gio 1</strong><span>ottobre · 7:45</span></div><div className="mapbox"><MapPin/><span>Mappa del locale</span></div><div className="summary-card"><div><span>Locale</span><b>L’ile Douce</b></div><div><span>Indirizzo</span><b>Via Porro Lambertenghi 15</b></div><div><span>Persone</span><b>5, tu compreso</b></div><div><span>Colazione</span><b>[DA DEFINIRE] €</b></div></div><Button variant="outline"><CalendarDays size={18}/> Aggiungi al calendario</Button>{!paid?<><div className="deadline-box"><Clock3 size={18}/><span>Conferma entro <b>martedì 29 settembre, 20:00</b>. Dopo il posto passa a un’altra persona.</span></div><Button onClick={()=>setPaid(true)}>Conferma e paga [prezzo] €</Button></>:<div className="success"><Check/> Pagamento riuscito. Il tuo posto è confermato.</div>}<div className="cancel-zone"><p>Non puoi più venire? Disdetta gratuita fino a <b>mercoledì 30 settembre, 19:45</b> (12 ore prima).</p><Button variant="dangerOutline" onClick={()=>setCancel(true)}>Disdici</Button></div></section></main>}

function Founder({go}){
 const [tab,setTab]=useState('Tavoli'); const tabs=['Disponibilità','Tavoli','Locali','Lista d’attesa','Segnalazioni','Iscritti'];
 return <div className="admin-shell"><aside><Logo/><nav>{tabs.map(t=><button className={tab===t?'active':''} onClick={()=>setTab(t)} key={t}>{t}{t==='Lista d’attesa'&&<span>12</span>}{t==='Segnalazioni'&&<span>2</span>}</button>)}</nav><div className="admin-note">Indicatori di genere ed età visibili solo qui.</div><button className="linkbtn" onClick={()=>go('home')}>← Esci dalla demo</button></aside><AdminContent tab={tab}/></div>
}
function AdminContent({tab}){
 if(tab==='Disponibilità') return <AdminPage title="Disponibilità" sub="Iscritti attivi, con abbonamento attivo e non in pausa."><div className="matrix"><div></div>{slots.map(s=><b key={s}>{s.replace(' · ','\n')}</b>)}{['Isola','Porta Venezia','Città Studi','Porta Romana'].flatMap((z,zi)=>[<strong key={z}>{z}</strong>,...slots.map((s,i)=><span className={(zi+i)%3===0?'hot':(zi+i)%2===0?'mid':''} key={z+s}>{[3,6,4,8,5,2,7,4][(zi*2+i)%8]}</span>)])}</div></AdminPage>;
 if(tab==='Locali') return <AdminPage title="Locali" sub="Partner disponibili per zona e slot."><div className="table"><div className="tr th"><span>Nome</span><span>Zona</span><span>Slot</span><span></span></div>{[['L’ile Douce','Isola','Mar/Gio · 7:45'],['Cafezal','Porta Venezia','Gio · 8:30'],['Marlà','Porta Romana','Mar · 8:30']].map(r=><div className="tr" key={r[0]}>{r.map(x=><span key={x}>{x}</span>)}<button>Modifica</button></div>)}</div><Button>+ Aggiungi locale</Button></AdminPage>;
 if(tab==='Lista d’attesa') return <AdminPage title="Lista d’attesa" sub="Approva quando una zona ha densità sufficiente."><div className="table people"><div className="tr th"><span>Nome</span><span>Lavoro</span><span>Zona</span><span>Azioni</span></div>{demoPeople.slice(0,4).map((p,i)=><div className="tr" key={p.name}><span><b>{p.name}</b><small>iscritto {24+i} set</small></span><span>{p.job}</span><span>{i%2?'Porta Venezia':'Isola'}</span><span className="actions"><button className="approve">Approva</button><button>Rifiuta</button></span></div>)}</div></AdminPage>;
 if(tab==='Segnalazioni') return <AdminPage title="Segnalazioni" sub="Le decisioni gravi richiedono sempre verifica umana."><div className="report-card"><Label tone="terra">2 RISCONTRI BASSI</Label><h3>Marco B.</h3><p>Tavolo · Isola · 24 settembre</p><div className="tags"><span>Voleva vendere qualcosa</span><span>Invadente</span></div><div className="report-actions"><Button variant="outline">Avvisa</Button><Button variant="dangerOutline">Sospendi</Button><Button variant="danger">Espelli</Button></div></div></AdminPage>;
 if(tab==='Iscritti') return <AdminPage title="Iscritti" sub="La media dei voti non è visibile agli iscritti."><div className="threshold"><span>Soglia media voti</span><strong>2,5 <small>/ 4</small></strong><span>3 persone sotto soglia</span></div><div className="table people"><div className="tr th"><span>Nome</span><span>Zona</span><span>Colazioni</span><span>Media</span></div>{demoPeople.map((p,i)=><div className="tr" key={p.name}><span><b>{p.name}</b><small>{p.job}</small></span><span>Isola</span><span>{3+i}</span><span className={i===1?'score low':'score'}>{i===1?'2,3':'3,'+(8-i)}</span></div>)}</div></AdminPage>;
 return <AdminPage title="Tavoli" sub="Le proposte restano bozza finché non assegni un locale e approvi gli inviti."><div className="table-card"><div className="table-card-head"><div><Label>PROPOSTA</Label><h2>Gio 1 ottobre · 7:45</h2><p>Isola · gruppo</p></div><span className="balance ok">Equilibrato</span></div><div className="participant-list">{demoPeople.map(p=><div key={p.name}><span className="initial">{p.name[0]}</span><div><b>{p.name}</b><small>{p.job}</small></div><span className="meta">{p.gender} · {p.age}</span></div>)}</div><div className="assign"><label>Locale<select defaultValue="L’ile Douce"><option>L’ile Douce</option><option>Cafezal</option></select></label><div className="balance-grid"><span>Genere <b>3 / 2</b></span><span>Età <b>29–41</b></span></div></div><div className="admin-actions"><Button variant="outline">Modifica</Button><Button>Invia inviti</Button></div></div></AdminPage>
}
function AdminPage({title,sub,children}){return <main className="admin-main"><header><div><Label>PANNELLO FONDATORE</Label><h1>{title}</h1><p>{sub}</p></div><button className="iconbtn"><Settings2/></button></header>{children}</main>}

function App(){const [screen,setScreen]=useState('home'); const screens={home:<PublicHome go={setScreen}/>,signup:<Signup go={setScreen}/>,waiting:<Waiting go={setScreen}/>,login:<Login go={setScreen}/>,member:<MemberHome go={setScreen}/>,invite:<Invitation go={setScreen}/>,founder:<Founder go={setScreen}/>};return screens[screen]||screens.home}

createRoot(document.getElementById('root')).render(<App/>);
